'use client';
import {useEffect,useMemo,useState} from 'react';
const CURS=[{code:'CAD',label:'Canadian Dollar',flag:'🇨🇦'},{code:'EUR',label:'Euro',flag:'🇪🇺'},{code:'TND',label:'Tunisian Dinar',flag:'🇹🇳'},{code:'USD',label:'US Dollar',flag:'🇺🇸'}] as const;
const fallback:Record<string,number>={CAD:1,EUR:.62,TND:2.09,USD:.73};
export default function CurrencyCard({currency}:{currency:string}){const [amount,setAmount]=useState(100);const [from,setFrom]=useState('CAD');const [to,setTo]=useState(CURS.some(x=>x.code===currency)?currency:'EUR');const [rates,setRates]=useState<Record<string,number>>(fallback);const [live,setLive]=useState(false);
useEffect(()=>{fetch('https://open.er-api.com/v6/latest/CAD').then(r=>r.ok?r.json():Promise.reject()).then(j=>{const next={...fallback};for(const c of CURS){if(c.code==='CAD')next.CAD=1;else if(j.rates?.[c.code])next[c.code]=j.rates[c.code]}setRates(next);setLive(true)}).catch(()=>{})},[]);
useEffect(()=>{if(CURS.some(x=>x.code===currency))setTo(currency)},[currency]);
const converted=useMemo(()=>amount/(rates[from]||1)*(rates[to]||1),[amount,from,to,rates]);const swap=()=>{setFrom(to);setTo(from)};
return <div className="card"><div className="eyebrow">CURRENCY</div><div className="grid grid2" style={{marginTop:10}}><label className="small muted">From<select className="input" value={from} onChange={e=>setFrom(e.target.value)}>{CURS.map(c=><option key={c.code} value={c.code}>{c.flag} {c.code} · {c.label}</option>)}</select></label><label className="small muted">To<select className="input" value={to} onChange={e=>setTo(e.target.value)}>{CURS.map(c=><option key={c.code} value={c.code}>{c.flag} {c.code} · {c.label}</option>)}</select></label></div><div className="currencyLine"><input className="input compact" type="number" min="0" value={amount} onChange={e=>setAmount(Number(e.target.value)||0)}/><strong>{from}</strong><button className="chip" onClick={swap} type="button">⇄</button></div><div className="metric">{converted.toFixed(2)} {to}</div><div className="muted">{live?'Live reference rate':'Planning-rate fallback'} · card/cash rates may differ</div><div className="quickAmounts">{[10,20,50,100,200].map(n=><button className="chip" key={n} onClick={()=>setAmount(n)} type="button">{n} {from}</button>)}</div></div>}
