import {verifiedRoutes} from '@/data/verifiedRoutes';
import {NavigationStop,plannedLegUrl,liveLegUrl,routeParts,routePartUrl} from '@/lib/routeNavigation';
export default function RouteNavigation({stops,mode='walking',next=1}:{stops:NavigationStop[];mode?:'walking'|'driving'|'transfer';next?:number}){
 if(stops.length<2)return null;
 if(mode==='transfer')return <p className="muted small">Cruise bus or taxi transfer first. Confirm the assigned cruise terminal and bus boarding point. Walking navigation begins with the separate city sections below.</p>;
 const live=next>0&&next<stops.length?liveLegUrl(stops[next],mode):null;
 return <div style={{marginTop:12}}>{stops[0].name==='Hotel de La Ville'&&stops[1]?.name==='Promenade'&&<ArrivalLoopNotes/>}<div className="actionRow">{live&&<a className="btn primary" href={live} target="_blank" rel="noreferrer">Google Maps · {mode==='walking'?'walk':'drive'} to next stop: {stops[next].name}</a>}{routeParts(stops).map((part,i)=>{const url=routePartUrl(part,mode);return url?<a className="btn" key={i} href={url} target="_blank" rel="noreferrer">Google Maps · part {i+1}: {part[0].name} → {part[part.length-1].name}</a>:<div className="soft" key={i}><strong>Part {i+1}: {part[0].name} → {part[part.length-1].name}</strong><div className="muted small">Directions unavailable until confirmed: {part.find(s=>s.confirm)?.confirm||'exact location'}. Begin at {part[0].name} and follow Bob’s notebook for this section; the next preview continues from {part[part.length-1].name}.</div></div>})}</div><div className="muted small" style={{marginTop:8}}>Preview parts follow the checklist in order and share their end/start point. “Next stop” uses your current location. The drawing shows stop order; Google chooses the streets. Notebook distance/time estimates may differ from Google’s current route.</div><details style={{marginTop:8}}><summary>Google Maps · every planned leg</summary>{stops.slice(1).map((to,i)=>{const from=stops[i],url=plannedLegUrl(from,to,mode);return <div className="row" key={i}><strong>{i+1}</strong><div>{from.name} → {to.name}{url?<div><a href={url} target="_blank" rel="noreferrer">Preview this {mode==='walking'?'walk':'taxi leg'}</a></div>:<div className="muted small">Meeting/location needs confirmation: {from.confirm||to.confirm||'exact address missing'}. No guessed directions.</div>}</div></div>})}</details></div>
}

function ArrivalLoopNotes(){
 const route=verifiedRoutes['2026-11-13'];
 const shortcut=plannedLegUrl(route[10],route[12],'walking');
 const legs=[['Promenade','260 m · 4 min'],['Falcone & Borsellino Monument','90 m · 1 min'],['Piazza della Vita','210 m · 3 min'],['Parco Flavio Gagliardini','93 m · 1 min'],['La Flama di Alfiero Antonini','800 m · 11 min'],['Il Bacio della Memoria di un Porto','92 m · 1 min'],['Forte Michelangelo','400 m · 6 min'],['Museo Archeologico Nazionale','270 m · 4 min'],['Return to Hotel de La Ville','400 m · 6 min']];
 return <aside className="soft" style={{marginBottom:16,padding:16,borderRadius:14}} aria-label="Bob’s November 13 walking notes"><div className="eyebrow">BOB’S ARRIVAL-DAY WALK · NOV 13</div><h3 style={{margin:'8px 0'}}>A waterfront loop back to your hotel</h3><div className="actionRow"><span className="pill">2.7 km · about 36 minutes walking</span><span className="pill">Start & finish · Hotel de La Ville</span></div><p>Bob’s promenade point means the waterfront approach toward the Falcone & Borsellino Monument. Follow the notebook’s seafront route; the exact entry pin still needs confirmation.</p><details style={{borderLeft:'3px solid #38d7c9',paddingLeft:12}}><summary><strong>Optional return shortcut · only after Forte Michelangelo</strong></summary><p style={{margin:'6px 0'}}>After Forte Michelangelo, return directly to Hotel de La Ville. Bob notes 500 metres / 7 minutes. This is an optional shortcut; the full checklist keeps the museum in its original position.</p>{shortcut&&<a className="btn" href={shortcut} target="_blank" rel="noreferrer">Google Maps · fort directly to hotel</a>}</details><details style={{marginTop:14}}><summary>Bob’s distances between stops</summary>{legs.map(([name,estimate],i)=><div className="row" key={name}><strong>{i+1}</strong><div>{name}<div className="muted small">{estimate} from the preceding point</div></div></div>)}<p className="muted small">Copied from Bob’s handwritten notes. The 2.7 km / 36 min total is his overall estimate; individual estimates are approximate and do not add up exactly. Allow extra time for sightseeing and breaks.</p></details></aside>
}
