'use client';
import {useMemo,useState} from 'react';

const LANGS:[string,string][]=[
['auto','Auto-detect'],['af','Afrikaans'],['sq','Albanian'],['am','Amharic'],['ar','Arabic'],['hy','Armenian'],['az','Azerbaijani'],['eu','Basque'],['be','Belarusian'],['bn','Bengali'],['bs','Bosnian'],['bg','Bulgarian'],['ca','Catalan'],['ceb','Cebuano'],['zh-CN','Chinese (Simplified)'],['zh-TW','Chinese (Traditional)'],['co','Corsican'],['hr','Croatian'],['cs','Czech'],['da','Danish'],['nl','Dutch'],['en','English'],['eo','Esperanto'],['et','Estonian'],['fi','Finnish'],['fr','French'],['fy','Frisian'],['gl','Galician'],['ka','Georgian'],['de','German'],['el','Greek'],['gu','Gujarati'],['ht','Haitian Creole'],['ha','Hausa'],['haw','Hawaiian'],['he','Hebrew'],['hi','Hindi'],['hmn','Hmong'],['hu','Hungarian'],['is','Icelandic'],['ig','Igbo'],['id','Indonesian'],['ga','Irish'],['it','Italian'],['ja','Japanese'],['jv','Javanese'],['kn','Kannada'],['kk','Kazakh'],['km','Khmer'],['rw','Kinyarwanda'],['ko','Korean'],['ku','Kurdish'],['ky','Kyrgyz'],['lo','Lao'],['la','Latin'],['lv','Latvian'],['lt','Lithuanian'],['lb','Luxembourgish'],['mk','Macedonian'],['mg','Malagasy'],['ms','Malay'],['ml','Malayalam'],['mt','Maltese'],['mi','Maori'],['mr','Marathi'],['mn','Mongolian'],['my','Myanmar (Burmese)'],['ne','Nepali'],['no','Norwegian'],['ny','Nyanja'],['or','Odia'],['ps','Pashto'],['fa','Persian'],['pl','Polish'],['pt','Portuguese'],['pa','Punjabi'],['ro','Romanian'],['ru','Russian'],['sm','Samoan'],['gd','Scots Gaelic'],['sr','Serbian'],['st','Sesotho'],['sn','Shona'],['sd','Sindhi'],['si','Sinhala'],['sk','Slovak'],['sl','Slovenian'],['so','Somali'],['es','Spanish'],['su','Sundanese'],['sw','Swahili'],['sv','Swedish'],['tl','Tagalog'],['tg','Tajik'],['ta','Tamil'],['tt','Tatar'],['te','Telugu'],['th','Thai'],['tr','Turkish'],['tk','Turkmen'],['uk','Ukrainian'],['ur','Urdu'],['ug','Uyghur'],['uz','Uzbek'],['vi','Vietnamese'],['cy','Welsh'],['xh','Xhosa'],['yi','Yiddish'],['yo','Yoruba'],['zu','Zulu']
];

export default function Translator({defaultTarget='it'}:{defaultTarget?:string}){
 const [source,setSource]=useState('auto');const [target,setTarget]=useState(defaultTarget);const [text,setText]=useState('');const [translated,setTranslated]=useState('');const [detected,setDetected]=useState('');const [status,setStatus]=useState('');
 const targetName=useMemo(()=>LANGS.find(x=>x[0]===target)?.[1]||target,[target]);
 async function translate(){if(!text.trim())return;setStatus('Translating…');try{const r=await fetch('/api/translate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({q:text,source,target})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Translation failed');setTranslated(j.translation||'');setDetected(j.detected||'');setStatus('Translated');}catch(e:any){setStatus(e?.message||'Translation unavailable. Internet connection is required.')}}
 function swap(){if(source==='auto'){setSource(target);setTarget('en');}else{setSource(target);setTarget(source);}setText(translated||text);setTranslated(text);}
 function speak(value:string,lang:string){if(!value||typeof speechSynthesis==='undefined')return;const u=new SpeechSynthesisUtterance(value);u.lang=lang==='auto'?'en':lang;speechSynthesis.cancel();speechSynthesis.speak(u)}
 function copy(){if(translated)navigator.clipboard?.writeText(translated);setStatus('Copied');}
 return <div className="card translatorCard"><div className="eyebrow">FULL TRANSLATOR</div><h2 className="sectionTitle" style={{marginTop:6}}>Translate almost any language</h2><div className="muted">Type or paste what you want to say. Internet is required for translation; pronunciation works on supported device voices.</div><div className="translatorLangRow"><select className="input" value={source} onChange={e=>setSource(e.target.value)}>{LANGS.map(([c,n])=><option value={c} key={c}>{n}</option>)}</select><button className="btn translatorSwap" onClick={swap} aria-label="Swap languages">⇄</button><select className="input" value={target} onChange={e=>setTarget(e.target.value)}>{LANGS.filter(x=>x[0]!=='auto').map(([c,n])=><option value={c} key={c}>{n}</option>)}</select></div><textarea className="input translatorText" rows={5} value={text} onChange={e=>setText(e.target.value)} placeholder="What would you like to translate?"/><div className="actionRow" style={{marginTop:10}}><button className="btn" onClick={()=>speak(text,source)}>🔊 Hear original</button><button className="btn primary" onClick={translate}>Translate</button></div><div className="translatorResult"><div className="eyebrow">{targetName.toUpperCase()}</div><div className="translatorOutput">{translated||'Your translation will appear here.'}</div>{detected&&<div className="muted small">Detected source: {detected}</div>}<div className="actionRow" style={{marginTop:10}}><button className="btn" onClick={()=>speak(translated,target)} disabled={!translated}>🔊 Hear translation</button><button className="btn" onClick={copy} disabled={!translated}>Copy</button></div></div><div className="muted small" style={{marginTop:10}}>{status}</div></div>
}
