'use client';
import {useEffect,useState} from 'react';

type TicketState={bobSeat:string;susanSeat:string};
const DEFAULT_SEATS:Record<string,TicketState>={'2026-11-12':{bobSeat:'05D',susanSeat:'05G'},'2026-11-26':{bobSeat:'05D / 5D',susanSeat:'05G / 5F'}};
const DB='bob-susan-travel-tickets';const STORE='tickets';
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getScan(id:string){const db=await openDb();return new Promise<Blob|undefined>((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result?.blob);r.onerror=()=>reject(r.error)})}
async function saveScan(id:string,blob:Blob){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id,blob});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}

const flights:{[key:string]:{title:string;segments:{time:string;route:string;detail:string}[]}}={
 '2026-11-12':{title:'OUTBOUND FLIGHT',segments:[{time:'8:25 PM',route:'Toronto Pearson (YYZ) → Rome Fiumicino (FCO)',detail:'Air Canada AC890 · Business Class · nonstop'},{time:'10:55 AM · Nov 13',route:'Arrive Rome FCO',detail:'Local arrival time'},{time:'Before departure',route:'YYZ lounge note',detail:'Air Canada advised the Signature Suite is temporarily closed. Signature-Suite-eligible customers are directed to the International Maple Leaf Lounge with priority access; a temporary pop-up is also noted at Gate E85.'}]},
 '2026-11-26':{title:'FLIGHTS HOME',segments:[{time:'6:50 AM',route:'Barcelona (BCN) → Frankfurt (FRA)',detail:'AC9183 · operated by Lufthansa · Airbus A321 · Business Class · BCN T1 → FRA T1 · arrive 9:00 AM'},{time:'10:05 AM',route:'Frankfurt (FRA) → Toronto Pearson (YYZ)',detail:'Air Canada AC841 · Boeing 777-300ER · Business Class · FRA T1 → YYZ T1 · arrive 12:45 PM'}]}
};

export default function TravelTransportCard({dayId}:{dayId:string}){
 const flight=flights[dayId];const isTrain=dayId==='2026-11-13';const key=`bs-flight-${dayId}`;
 const [seats,setSeats]=useState<TicketState>(DEFAULT_SEATS[dayId]||{bobSeat:'',susanSeat:''});const [scanUrl,setScanUrl]=useState('');const [status,setStatus]=useState('');
 useEffect(()=>{if(!flight)return;try{setSeats(JSON.parse(localStorage.getItem(key)||JSON.stringify(DEFAULT_SEATS[dayId]||{bobSeat:'',susanSeat:''})))}catch{};getScan(dayId).then(b=>{if(b)setScanUrl(URL.createObjectURL(b))}).catch(()=>{});return()=>{if(scanUrl)URL.revokeObjectURL(scanUrl)}},[dayId]);
 function saveSeats(next:TicketState){setSeats(next);localStorage.setItem(key,JSON.stringify(next));setStatus('Seat numbers saved on this device.')}
 async function addScan(file?:File){if(!file)return;await saveScan(dayId,file);if(scanUrl)URL.revokeObjectURL(scanUrl);setScanUrl(URL.createObjectURL(file));setStatus('Ticket / boarding pass scan saved privately on this device.')}
 if(!flight&&!isTrain)return null;
 return <div className="card" style={{borderColor:'#3e6f7d'}}>{isTrain?<><div className="eyebrow">TRAIN SCHEDULE · NOV 13</div><h2 className="sectionTitle" style={{marginTop:6}}>Rome FCO → Civitavecchia</h2><div className="row"><strong>11:42 AM</strong><div><strong>Regionale 20641 · Fiumicino Aeroporto → Roma Trastevere</strong><div className="muted">Arrive 12:09 PM · Bob notes one stop at Ostiense · 2nd class · seating not reserved</div></div></div><div className="row"><strong>12:28 PM</strong><div><strong>Regionale 12642 · Roma Trastevere → Civitavecchia</strong><div className="muted">Arrive 1:25 PM · 19-minute connection · 2nd class · seating not reserved</div></div></div><div className="soft" style={{marginTop:12,padding:12}}><strong>Station → Hotel de La Ville · 400 m / about 5 minutes</strong><p style={{margin:"6px 0"}}>Follow Bob’s map via Via Francesco Crispi and Via Santa Fermina to Viale della Repubblica 4. Double Room with Sea View · stay November 13–15.</p><a href="tel:+390766580507">Call hotel · +39 0766 580507</a></div><div className="muted small" style={{marginTop:8}}>These are personal Regional Digital Tickets for Bob and Susan. Trenitalia notes automatic ticket validation at the scheduled departure time. Keep the live departure board handy for platform or schedule changes.</div></>:<><div className="eyebrow">{flight.title}</div><h2 className="sectionTitle" style={{marginTop:6}}>{dayId==='2026-11-12'?'Air Canada AC890':'Barcelona → Frankfurt → Toronto'}</h2>{flight.segments.map((s,i)=><div className="row" key={i}><strong>{s.time}</strong><div><strong>{s.route}</strong><div className="muted">{s.detail}</div></div></div>)}<div className="soft" style={{marginTop:12}}><div className="eyebrow">SEATS · SAVED ON THIS DEVICE</div><div className="grid grid2" style={{marginTop:8}}><label><span className="muted small">Bob {dayId==='2026-11-26'?'(FRA→YYZ / BCN→FRA)':''}</span><input className="input" value={seats.bobSeat} onChange={e=>saveSeats({...seats,bobSeat:e.target.value})} placeholder="Seat number"/></label><label><span className="muted small">Susan {dayId==='2026-11-26'?'(FRA→YYZ / BCN→FRA)':''}</span><input className="input" value={seats.susanSeat} onChange={e=>saveSeats({...seats,susanSeat:e.target.value})} placeholder="Seat number"/></label></div><div className="actionRow" style={{marginTop:10}}><label className="btn"><input hidden type="file" accept="image/*" capture="environment" onChange={e=>addScan(e.target.files?.[0])}/>📷 Add / scan ticket</label></div>{scanUrl&&<img src={scanUrl} alt="Saved ticket or boarding pass" style={{width:'100%',marginTop:10,borderRadius:14}}/>}<div className="muted small" style={{marginTop:8}}>Ticket images and seat numbers stay on this phone. They are not added to the public website code.</div>{status&&<div className="muted small" style={{marginTop:8}}>{status}</div>}</div></>}</div>
}
