'use client';
import {useEffect,useMemo,useState} from 'react';
import Header from '@/components/Header';
import {clearPrivateDocuments,deletePrivateDocument,listPrivateDocuments,PrivateDocumentKind,PrivateDocumentRecord,savePrivateDocument} from '@/lib/privateDocumentStore';

const PIN_KEY='bs-documents-pin-v1';
async function hashPin(pin:string){const data=new TextEncoder().encode(pin);const hash=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function labelFor(kind:PrivateDocumentKind){return kind==='passport'?'Passport':kind==='health'?'Health card':kind==='insurance'?'Travel insurance':kind==='id'?'ID':'Other'}
async function ensureTesseract(){if((window as any).Tesseract)return (window as any).Tesseract;await new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=()=>resolve();s.onerror=()=>reject(new Error('OCR engine could not load'));document.head.appendChild(s)});return (window as any).Tesseract}
function isoDateFromText(text:string,near?:RegExp){
 const source=near?(text.split(/\r?\n/).find(x=>near.test(x))||text):text;
 const ymd=source.match(/\b(20\d{2})[-\/.](\d{1,2})[-\/.](\d{1,2})\b/);if(ymd)return ymd[1]+'-'+ymd[2].padStart(2,'0')+'-'+ymd[3].padStart(2,'0');
 const dmy=source.match(/\b(\d{1,2})[-\/.](\d{1,2})[-\/.](20\d{2})\b/);if(dmy)return dmy[3]+'-'+dmy[2].padStart(2,'0')+'-'+dmy[1].padStart(2,'0');
 const month=source.match(/\b(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+(\d{1,2}),?\s+(20\d{2})\b/i);
 if(month){const m=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'].indexOf(month[1].slice(0,3).toLowerCase())+1;return month[3]+'-'+String(m).padStart(2,'0')+'-'+month[2].padStart(2,'0')}
 return '';
}
function extractPhone(text:string){const line=text.split(/\r?\n/).find(x=>/(emergency|assistance|help|contact)/i.test(x)&&/[\d() +.-]{10,}/.test(x));const m=(line||text).match(/(?:\+?\d[\d() .-]{8,}\d)/);return m?m[0].replace(/\s+/g,' ').trim():''}
function extractIssuer(text:string,kind:PrivateDocumentKind){
 const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
 if(kind==='insurance'){return lines.find(x=>/(CAA|Manulife|Allianz|Blue Cross|Travel Guard|RBC|TD Insurance|Sun Life)/i.test(x))||''}
 if(kind==='health'){return lines.find(x=>/(Ontario|OHIP|Health|Ministry of Health)/i.test(x))||''}
 if(kind==='passport'||kind==='id'){return lines.find(x=>/(Canada|Canadian|Passport|Government)/i.test(x))||''}
 return '';
}
function extractNationality(text:string){if(/\bCAN(?:ADA|ADIAN)?\b/i.test(text))return 'Canada';return ''}
function extractCoverageStart(text:string){const lines=text.split(/\r?\n/);const hit=lines.find(x=>/(effective|coverage|start|from)/i.test(x));return isoDateFromText(hit||'')}
function parseDocument(text:string,kind:PrivateDocumentKind,person:'Bob'|'Susan'|'Both'){
 const issuer=extractIssuer(text,kind);const nationality=extractNationality(text);
 const expiry=isoDateFromText(text,/(expir|valid until|expiry|end date)/i);
 const coverageStart=kind==='insurance'?extractCoverageStart(text):'';
 const emergencyPhone=kind==='insurance'?extractPhone(text):'';
 const basePerson=person==='Both'?'Bob & Susan':person;
 let title=basePerson+' '+labelFor(kind).toLowerCase();
 if(kind==='health'&&/Ontario|OHIP/i.test(text))title=basePerson+' Ontario health card';
 if(kind==='insurance'&&issuer)title=basePerson+' '+issuer.replace(/\s+/g,' ').trim()+' travel insurance';
 const bits:string[]=[];if(issuer)bits.push('Issuer: '+issuer);if(nationality)bits.push('Nationality: '+nationality);if(coverageStart)bits.push('Coverage starts: '+coverageStart);
 return{title,expiry,emergencyPhone,issuer,nationality,coverageStart,notes:bits.join('\n')};
}

export default function Documents(){
 const [docs,setDocs]=useState<PrivateDocumentRecord[]>([]);const [unlocked,setUnlocked]=useState(false);const [pin,setPin]=useState('');const [pinSet,setPinSet]=useState(false);const [pinMsg,setPinMsg]=useState('');
 const [person,setPerson]=useState<'Bob'|'Susan'|'Both'>('Bob');const [kind,setKind]=useState<PrivateDocumentKind>('passport');const [title,setTitle]=useState('');const [notes,setNotes]=useState('');const [expiry,setExpiry]=useState('');const [emergencyPhone,setEmergencyPhone]=useState('');const [issuer,setIssuer]=useState('');const [nationality,setNationality]=useState('');const [coverageStart,setCoverageStart]=useState('');const [file,setFile]=useState<File|null>(null);const [status,setStatus]=useState('');const [ocrStatus,setOcrStatus]=useState('');const [deleteText,setDeleteText]=useState('');
 const [urls,setUrls]=useState<Record<string,string>>({});
 useEffect(()=>{setPinSet(!!localStorage.getItem(PIN_KEY))},[]);
 useEffect(()=>{const next:Record<string,string>={};docs.forEach(d=>{if(d.blob)next[d.id]=URL.createObjectURL(d.blob)});setUrls(next);return()=>Object.values(next).forEach(URL.revokeObjectURL)},[docs]);
 async function unlockOrCreate(){if(!/^\d{4,6}$/.test(pin)){setPinMsg('Use a 4–6 digit PIN.');return}const h=await hashPin(pin);const saved=localStorage.getItem(PIN_KEY);if(saved&&saved!==h){setPinMsg('Incorrect PIN.');return}if(!saved){localStorage.setItem(PIN_KEY,h);setPinSet(true)}setUnlocked(true);setPin('');setPinMsg('');setDocs(await listPrivateDocuments())}
 async function scanFile(nextFile:File){setFile(nextFile);setOcrStatus('Reading the document on this phone…');if(!nextFile.type.startsWith('image/')){setOcrStatus('PDF saved for review. Auto-fill currently works best from a photo or image.');return}try{const T=await ensureTesseract();const result=await T.recognize(nextFile,'eng');const parsed=parseDocument(String(result?.data?.text||''),kind,person);if(parsed.title)setTitle(parsed.title);if(parsed.expiry)setExpiry(parsed.expiry);if(parsed.emergencyPhone)setEmergencyPhone(parsed.emergencyPhone);if(parsed.issuer)setIssuer(parsed.issuer);if(parsed.nationality)setNationality(parsed.nationality);if(parsed.coverageStart)setCoverageStart(parsed.coverageStart);if(parsed.notes)setNotes(parsed.notes);setOcrStatus('We found this information. Please review it below, then tap the big Save button.')}catch{setOcrStatus('I could not read this clearly. The photo is still attached and you can correct or enter the fields below.')}}
 async function addDoc(){if(!title.trim()){setStatus('Add or confirm the document title first.');return}const now=new Date().toISOString();const doc:PrivateDocumentRecord={id:crypto.randomUUID(),person,kind,title:title.trim(),notes:notes.trim()||undefined,expiry:expiry||undefined,emergencyPhone:emergencyPhone.trim()||undefined,issuer:issuer.trim()||undefined,nationality:nationality.trim()||undefined,coverageStart:coverageStart||undefined,blob:file||undefined,mime:file?.type,fileName:file?.name,createdAt:now,updatedAt:now};await savePrivateDocument(doc);setDocs(await listPrivateDocuments());setTitle('');setNotes('');setExpiry('');setEmergencyPhone('');setIssuer('');setNationality('');setCoverageStart('');setFile(null);setOcrStatus('');setStatus('✓ Saved privately on this device.')}
 async function remove(id:string){await deletePrivateDocument(id);setDocs(await listPrivateDocuments())}
 async function wipe(){if(deleteText!=='DELETE')return;await clearPrivateDocuments();setDocs([]);setDeleteText('');setStatus('Private documents on this device were deleted.')}
 const grouped=useMemo(()=>['passport','health','insurance','id','other'].map(k=>({kind:k as PrivateDocumentKind,items:docs.filter(d=>d.kind===k)})).filter(g=>g.items.length),[docs]);

 if(!unlocked)return <><Header subtitle="Private travel wallet"/><div className="card" style={{maxWidth:520,margin:'0 auto'}}><div className="eyebrow">PRIVATE DOCUMENTS</div><h2 className="sectionTitle" style={{marginTop:6}}>{pinSet?'Unlock travel wallet':'Create a travel-wallet PIN'}</h2><div className="muted">{pinSet?'Enter the PIN created on this device.':'Choose a 4–6 digit PIN. The wallet stays on this device and is not added to GitHub.'}</div><input className="input" inputMode="numeric" pattern="[0-9]*" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="4–6 digit PIN" style={{marginTop:12}}/><button className="btn primary" type="button" onClick={unlockOrCreate} style={{marginTop:10,fontSize:18,padding:'14px 18px'}}>{pinSet?'Unlock':'Create PIN & open'}</button>{pinMsg&&<div className="muted small" style={{marginTop:8}}>{pinMsg}</div>}<div className="muted small" style={{marginTop:14}}>This PIN is an app-level privacy screen. It is not the same as Face ID or full device encryption. The scans stay in this browser’s local storage on this phone.</div></div></>;

 return <><Header subtitle="Passports · health cards · insurance · IDs"/><div className="card" style={{borderColor:'#4f725f'}}><div className="eyebrow">PRIVATE TRAVEL WALLET</div><h2 className="sectionTitle" style={{marginTop:6}}>Bob & Susan’s documents</h2><div className="muted">Take a photo and the app will try to fill the form automatically. The photo is read on this device; it is not uploaded to the public website or GitHub.</div><div className="soft" style={{marginTop:10}}>CAA travel insurance coverage: Nov 12–26, 2026</div><div className="actionRow" style={{marginTop:10}}><button className="btn" type="button" onClick={()=>setUnlocked(false)}>🔒 Lock wallet</button></div></div><div className="spacer"/>
 <div className="card"><div className="eyebrow">1 · CHOOSE DOCUMENT</div><div className="grid grid2" style={{marginTop:10}}><label><span className="muted small">Person</span><select className="input" value={person} onChange={e=>setPerson(e.target.value as 'Bob'|'Susan'|'Both')}><option>Bob</option><option>Susan</option><option>Both</option></select></label><label><span className="muted small">Type</span><select className="input" value={kind} onChange={e=>setKind(e.target.value as PrivateDocumentKind)}><option value="passport">Passport</option><option value="health">Health card</option><option value="insurance">Travel insurance</option><option value="id">ID</option><option value="other">Other</option></select></label></div><label className="btn primary" style={{marginTop:14,fontSize:18,padding:'15px 18px',display:'inline-flex'}}><input hidden type="file" accept="image/*,application/pdf" capture="environment" onChange={e=>{const x=e.target.files?.[0];if(x)scanFile(x)}}/>📷 Take photo / choose document</label>{ocrStatus&&<div className="soft" style={{marginTop:12,borderLeft:'4px solid var(--accent)'}}><strong>{ocrStatus.startsWith('We found')?'✓ We found this information':'Document scan'}</strong><div className="muted small" style={{marginTop:5}}>{ocrStatus}</div></div>}</div>
 <div className="spacer"/><div className="card"><div className="eyebrow">2 · REVIEW WHAT WE FOUND</div><h2 className="sectionTitle" style={{marginTop:6}}>Check these details</h2><div className="muted small">Change anything that does not look right. Nothing is saved until you tap Save below.</div><label><span className="muted small">Title</span><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Bob passport"/></label><div className="grid grid2"><label><span className="muted small">Issuer / organization</span><input className="input" value={issuer} onChange={e=>setIssuer(e.target.value)} placeholder="e.g. Canada / CAA"/></label><label><span className="muted small">Nationality</span><input className="input" value={nationality} onChange={e=>setNationality(e.target.value)} placeholder="For passport / ID"/></label><label><span className="muted small">Expiry / coverage end</span><input className="input" type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label><span className="muted small">Coverage start</span><input className="input" type="date" value={coverageStart} onChange={e=>setCoverageStart(e.target.value)}/></label><label><span className="muted small">Emergency phone</span><input className="input" value={emergencyPhone} onChange={e=>setEmergencyPhone(e.target.value)} placeholder="+1 ..."/></label></div><label><span className="muted small">Notes</span><textarea className="input" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional"/></label><button className="btn primary" type="button" onClick={addDoc} style={{marginTop:14,fontSize:19,padding:'16px 20px',width:'100%'}}>✓ Looks right — Save document</button>{status&&<div className="soft" style={{marginTop:10}}>{status}</div>}</div>
 <div className="spacer"/>{grouped.length?grouped.map(g=><div className="card" key={g.kind} style={{marginBottom:12}}><div className="eyebrow">{labelFor(g.kind).toUpperCase()}</div>{g.items.map(d=><div className="row" key={d.id}><div style={{flex:1}}><strong>{d.person} · {d.title}</strong>{d.issuer&&<div className="muted small">Issuer: {d.issuer}</div>}{d.nationality&&<div className="muted small">Nationality: {d.nationality}</div>}{d.coverageStart&&<div className="muted small">Coverage starts: {d.coverageStart}</div>}{d.expiry&&<div className="muted small">Expiry / end: {d.expiry}</div>}{d.emergencyPhone&&<div className="muted small">Emergency: <a href={'tel:'+d.emergencyPhone}>{d.emergencyPhone}</a></div>}{d.notes&&<div className="muted small" style={{marginTop:4,whiteSpace:'pre-line'}}>{d.notes}</div>}<div className="actionRow" style={{marginTop:8}}>{urls[d.id]&&<a className="btn" href={urls[d.id]} target="_blank" rel="noreferrer">Open scan</a>}<button className="btn" type="button" onClick={()=>remove(d.id)}>Delete</button></div></div></div>)}</div>):<div className="card"><div className="muted">No private documents saved on this device yet.</div></div>}
 <div className="spacer"/><div className="card" style={{borderColor:'#6f4747'}}><div className="eyebrow">DELETE PRIVATE WALLET</div><div className="muted small">The normal pre-trip Clean Slate reset does not delete this document wallet. To erase all private documents on this device, type <strong>DELETE</strong>.</div><input className="input" value={deleteText} onChange={e=>setDeleteText(e.target.value)} placeholder="Type DELETE" style={{marginTop:10}}/><button className="btn" type="button" disabled={deleteText!=='DELETE'} onClick={wipe} style={{marginTop:10,borderColor:'#a35b5b'}}>Delete all private documents</button></div></>
}
