'use client';
import {useEffect,useMemo,useState} from 'react';
import Header from '@/components/Header';
import {clearPrivateDocuments,deletePrivateDocument,listPrivateDocuments,PrivateDocumentKind,PrivateDocumentRecord,savePrivateDocument} from '@/lib/privateDocumentStore';

const PIN_KEY='bs-documents-pin-v1';
async function hashPin(pin:string){const data=new TextEncoder().encode(pin);const hash=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function labelFor(kind:PrivateDocumentKind){return kind==='passport'?'Passport':kind==='health'?'Health card':kind==='insurance'?'Travel insurance':kind==='id'?'ID':'Other'}

export default function Documents(){
 const [docs,setDocs]=useState<PrivateDocumentRecord[]>([]);const [unlocked,setUnlocked]=useState(false);const [pin,setPin]=useState('');const [pinSet,setPinSet]=useState(false);const [pinMsg,setPinMsg]=useState('');
 const [person,setPerson]=useState<'Bob'|'Susan'|'Both'>('Bob');const [kind,setKind]=useState<PrivateDocumentKind>('passport');const [title,setTitle]=useState('');const [notes,setNotes]=useState('');const [expiry,setExpiry]=useState('');const [emergencyPhone,setEmergencyPhone]=useState('');const [file,setFile]=useState<File|null>(null);const [status,setStatus]=useState('');const [deleteText,setDeleteText]=useState('');
 const [urls,setUrls]=useState<Record<string,string>>({});
 useEffect(()=>{setPinSet(!!localStorage.getItem(PIN_KEY))},[]);
 useEffect(()=>{const next:Record<string,string>={};docs.forEach(d=>{if(d.blob)next[d.id]=URL.createObjectURL(d.blob)});setUrls(next);return()=>Object.values(next).forEach(URL.revokeObjectURL)},[docs]);
 async function unlockOrCreate(){if(!/^\d{4,6}$/.test(pin)){setPinMsg('Use a 4–6 digit PIN.');return}const h=await hashPin(pin);const saved=localStorage.getItem(PIN_KEY);if(saved&&saved!==h){setPinMsg('Incorrect PIN.');return}if(!saved){localStorage.setItem(PIN_KEY,h);setPinSet(true)}setUnlocked(true);setPin('');setPinMsg('');setDocs(await listPrivateDocuments())}
 async function addDoc(){if(!title.trim()){setStatus('Add a document title first.');return}const now=new Date().toISOString();const doc:PrivateDocumentRecord={id:crypto.randomUUID(),person,kind,title:title.trim(),notes:notes.trim()||undefined,expiry:expiry||undefined,emergencyPhone:emergencyPhone.trim()||undefined,blob:file||undefined,mime:file?.type,fileName:file?.name,createdAt:now,updatedAt:now};await savePrivateDocument(doc);setDocs(await listPrivateDocuments());setTitle('');setNotes('');setExpiry('');setEmergencyPhone('');setFile(null);setStatus('Saved privately on this device.')}
 async function remove(id:string){await deletePrivateDocument(id);setDocs(await listPrivateDocuments())}
 async function wipe(){if(deleteText!=='DELETE')return;await clearPrivateDocuments();setDocs([]);setDeleteText('');setStatus('Private documents on this device were deleted.')}
 const grouped=useMemo(()=>['passport','health','insurance','id','other'].map(k=>({kind:k as PrivateDocumentKind,items:docs.filter(d=>d.kind===k)})).filter(g=>g.items.length),[docs]);

 if(!unlocked)return <><Header subtitle="Private travel wallet"/><div className="card" style={{maxWidth:520,margin:'0 auto'}}><div className="eyebrow">PRIVATE DOCUMENTS</div><h2 className="sectionTitle" style={{marginTop:6}}>{pinSet?'Unlock travel wallet':'Create a travel-wallet PIN'}</h2><div className="muted">{pinSet?'Enter the PIN created on this device.':'Choose a 4–6 digit PIN. The wallet stays on this device and is not added to GitHub.'}</div><input className="input" inputMode="numeric" pattern="[0-9]*" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="4–6 digit PIN" style={{marginTop:12}}/><button className="btn primary" type="button" onClick={unlockOrCreate} style={{marginTop:10}}>{pinSet?'Unlock':'Create PIN & open'}</button>{pinMsg&&<div className="muted small" style={{marginTop:8}}>{pinMsg}</div>}<div className="muted small" style={{marginTop:14}}>This PIN is an app-level privacy screen. It is not the same as Face ID or full device encryption. The scans stay in this browser’s local storage on this phone.</div></div></>;

 return <><Header subtitle="Passports · health cards · insurance · IDs"/><div className="card" style={{borderColor:'#4f725f'}}><div className="eyebrow">PRIVATE TRAVEL WALLET</div><h2 className="sectionTitle" style={{marginTop:6}}>Bob & Susan’s documents</h2><div className="muted">Scans and private details are stored locally on this device. They are not committed to the public website or GitHub.</div><div className="soft" style={{marginTop:10}}>CAA travel insurance coverage: Nov 12–26, 2026</div><div className="actionRow" style={{marginTop:10}}><button className="btn" type="button" onClick={()=>setUnlocked(false)}>🔒 Lock wallet</button></div></div><div className="spacer"/>
 <div className="card"><div className="eyebrow">ADD DOCUMENT</div><div className="grid grid2" style={{marginTop:10}}><label><span className="muted small">Person</span><select className="input" value={person} onChange={e=>setPerson(e.target.value as 'Bob'|'Susan'|'Both')}><option>Bob</option><option>Susan</option><option>Both</option></select></label><label><span className="muted small">Type</span><select className="input" value={kind} onChange={e=>setKind(e.target.value as PrivateDocumentKind)}><option value="passport">Passport</option><option value="health">Health card</option><option value="insurance">Travel insurance</option><option value="id">ID</option><option value="other">Other</option></select></label></div><label><span className="muted small">Title</span><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Bob passport"/></label><div className="grid grid2"><label><span className="muted small">Expiry / end date</span><input className="input" type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label><span className="muted small">Emergency phone (optional)</span><input className="input" value={emergencyPhone} onChange={e=>setEmergencyPhone(e.target.value)} placeholder="+1 ..."/></label></div><label><span className="muted small">Notes / policy summary</span><textarea className="input" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional details. Avoid putting anything here you do not need."/></label><label className="btn" style={{marginTop:10}}><input hidden type="file" accept="image/*,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/>📎 {file?('Selected: '+file.name):'Add scan / photo / PDF'}</label><div className="actionRow" style={{marginTop:10}}><button className="btn primary" type="button" onClick={addDoc}>Save privately on this device</button></div>{status&&<div className="soft" style={{marginTop:10}}>{status}</div>}</div>
 <div className="spacer"/>{grouped.length?grouped.map(g=><div className="card" key={g.kind} style={{marginBottom:12}}><div className="eyebrow">{labelFor(g.kind).toUpperCase()}</div>{g.items.map(d=><div className="row" key={d.id}><div style={{flex:1}}><strong>{d.person} · {d.title}</strong>{d.expiry&&<div className="muted small">Expiry / end: {d.expiry}</div>}{d.emergencyPhone&&<div className="muted small">Emergency: <a href={'tel:'+d.emergencyPhone}>{d.emergencyPhone}</a></div>}{d.notes&&<div className="muted small" style={{marginTop:4}}>{d.notes}</div>}<div className="actionRow" style={{marginTop:8}}>{urls[d.id]&&<a className="btn" href={urls[d.id]} target="_blank" rel="noreferrer">Open scan</a>}<button className="btn" type="button" onClick={()=>remove(d.id)}>Delete</button></div></div></div>)}</div>):<div className="card"><div className="muted">No private documents saved on this device yet.</div></div>}
 <div className="spacer"/><div className="card" style={{borderColor:'#6f4747'}}><div className="eyebrow">DELETE PRIVATE WALLET</div><div className="muted small">The normal pre-trip Clean Slate reset does not delete this document wallet. To erase all private documents on this device, type <strong>DELETE</strong>.</div><input className="input" value={deleteText} onChange={e=>setDeleteText(e.target.value)} placeholder="Type DELETE" style={{marginTop:10}}/><button className="btn" type="button" disabled={deleteText!=='DELETE'} onClick={wipe} style={{marginTop:10,borderColor:'#a35b5b'}}>Delete all private documents</button></div></>
}
