create extension if not exists pgcrypto;
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, role text default 'traveler', created_at timestamptz default now());
create table if not exists trips (id uuid primary key default gen_random_uuid(), title text not null, start_date date, end_date date, created_at timestamptz default now());
create table if not exists trip_members (trip_id uuid references trips(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, role text default 'traveler', primary key(trip_id,user_id));
create table if not exists trip_days (id uuid primary key default gen_random_uuid(), trip_id uuid references trips(id) on delete cascade, day_date date not null, city text, country text, currency text, timezone text, ship_arrival time, ship_departure time, all_aboard time, weather_note text, tipping_note text, emergency_note text, phrase_native text, phrase_english text, notes text);
create table if not exists places (id uuid primary key default gen_random_uuid(), trip_id uuid references trips(id) on delete cascade, name text not null, city text, country text, latitude double precision, longitude double precision, description text);
create table if not exists events (id uuid primary key default gen_random_uuid(), trip_day_id uuid references trip_days(id) on delete cascade, event_type text, title text not null, start_time time, end_time time, place_id uuid references places(id), notes text);
create table if not exists routes (id uuid primary key default gen_random_uuid(), trip_day_id uuid references trip_days(id) on delete cascade, title text not null);
create table if not exists route_stops (id uuid primary key default gen_random_uuid(), route_id uuid references routes(id) on delete cascade, place_id uuid references places(id), stop_order int not null, note text, completed_at timestamptz);
create table if not exists reservations (id uuid primary key default gen_random_uuid(), trip_day_id uuid references trip_days(id) on delete cascade, reservation_type text, title text not null, reservation_time time, confirmation_note text);
create table if not exists memories (id uuid primary key default gen_random_uuid(), trip_day_id uuid references trip_days(id) on delete set null, place_id uuid references places(id) on delete set null, user_id uuid references auth.users(id), photo_path text, latitude double precision, longitude double precision, taken_at timestamptz, ai_landmark_name text, ai_description text, confidence numeric, confirmed boolean default false, personal_note text, transcript text, favorite boolean default false, created_at timestamptz default now());
create table if not exists documents (id uuid primary key default gen_random_uuid(), trip_id uuid references trips(id) on delete cascade, user_id uuid references auth.users(id), document_type text, title text not null, storage_path text not null, private boolean default true, created_at timestamptz default now());
create table if not exists settings (trip_id uuid references trips(id) on delete cascade, key text, value jsonb, primary key(trip_id,key));
alter table profiles enable row level security;alter table trip_members enable row level security;alter table trip_days enable row level security;alter table places enable row level security;alter table events enable row level security;alter table routes enable row level security;alter table route_stops enable row level security;alter table reservations enable row level security;alter table memories enable row level security;alter table documents enable row level security;alter table settings enable row level security;
-- Add policies after Bob, Susan and admin accounts are created. Use trip_members to gate each trip.
-- Storage buckets recommended: memories (private), documents (private).
